name: EnchantedBook
version: "${version}"
main: moe.minacle.minecraft.plugins.enchantedbook.Plugin
description: A plugin to extract enchantments from your armour into an Enchanted Book using the anvil.
authors:
  - Minacle
website: https://modrinth.com/plugin/enchantedbook
api-version: "1.21"
folia-supported: true
